name: Pipeline for Notification Code Microservice

on:
  push:
    branches:
      - test
    paths:
      - 'code-service/**'
      - '.github/workflows/code-pipeline.yml'
  pull_request:
    branches: 
      - test
    paths:
      - 'code-service/**'
      - '.github/workflows/code-pipeline.yml'
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_CODE}}:latest ./code-service

      - name: Push Docker image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_CODE}}:latest

  deploy-to-ec2-instance:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Export secrets as environment variables"
            export EMAIL_FROM="${{ secrets.EMAIL_FROM }}"
            export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
            export LOGO_URL="${{ secrets.LOGO_URL }}"
            export WEBSOCKET_URL="${{ secrets.WEBSOCKET_URL }}"
            export DOCKER_IMAGE_CODE="${{ secrets.DOCKER_IMAGE_CODE }}"
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"

            echo "Pull, stop, and redeploy the Docker container"
            docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_CODE:latest

            echo "Stopping and removing existing container if it exists"
            docker stop $DOCKER_IMAGE_CODE || true
            docker rm $DOCKER_IMAGE_CODE || true

            echo "Running new Docker container"
            docker run --restart always \
                      -e EMAIL_FROM=$EMAIL_FROM \
                      -e EMAIL_PASSWORD=$EMAIL_PASSWORD \
                      -e LOGO_URL=$LOGO_URL \
                      -e WEBSOCKET_URL=$WEBSOCKET_URL \
                      -d --name $DOCKER_IMAGE_CODE \
                      -p 80:80 $DOCKER_USERNAME/$DOCKER_IMAGE_CODE:latest