name: Pipeline for Notification Action Microservice

on:
  push:
    branches:
      - test
    paths:
      - 'notification-action-service/**'
      - '.github/workflows/notification-action-pipeline.yml'
  pull_request:
    branches: 
      - test
    paths:
      - 'notification-action-service/**'
      - '.github/workflows/notification-action-pipeline.yml'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_ACT}}:latest ./notification-action-service

      - name: Push Docker image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_ACT}}:latest

  deploy-to-ec2-instance:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Log in to Docker Hub"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            echo "Pull, stop, and redeploy the Docker container"
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_ACT }}:latest

            if docker ps -a --filter "name=${{secrets.DOCKER_IMAGE_ACT}}" | grep -q ${{secrets.DOCKER_IMAGE_ACT}}; then
              docker stop ${{secrets.DOCKER_IMAGE_ACT}}
              docker rm ${{secrets.DOCKER_IMAGE_ACT}}
            fi

            docker run --restart always \
                       -e EMAIL_FROM=${{secrets.EMAIL_FROM}} \
                       -e EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}} \
                       -e LOGO_URL=${{secrets.LOGO_URL}} \
                       -e WEBSOCKET_URL=${{secrets.WEBSOCKET_URL}} \
                       -d --name ${{secrets.DOCKER_IMAGE_ACT}} \
                       -p 1028:1028 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_ACT}}:latest